# Generated by Django 4.0.4 on 2022-04-23 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TempahanSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempahan_enable', models.BooleanField(default=True)),
                ('pengesaan_diperlukan', models.BooleanField(default=True)),
                ('matikan_hujung_minggu', models.BooleanField(default=True)),
                ('tempahan_available_sebulan', models.IntegerField(default=True)),
                ('max_tempahan_per_hari', models.IntegerField(blank=True, null=True)),
                ('masa_mula', models.TimeField()),
                ('masa_tamat', models.TimeField()),
                ('period_setiap_tempahan', models.CharField(choices=[('5', '5M'), ('10', '10M'), ('15', '15M'), ('20', '20M'), ('25', '25M'), ('30', '30M'), ('35', '35M'), ('40', '40M'), ('45', '45M'), ('60', '1H'), ('75', '1H 15M'), ('90', '1H 30M'), ('105', '1H 45M'), ('120', '2H'), ('150', '2H 30M'), ('180', '3H')], default=30, help_text='Berapa lama setiap tempahan diambil', max_length=200)),
                ('max_tempahan_per_masa', models.IntegerField(default=1, help_text='Berapa banyak temujanji boleh tempah dalam setiap satu satu masa')),
            ],
        ),
        migrations.CreateModel(
            name='Tempahan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarikh', models.DateTimeField()),
                ('masa', models.TimeField()),
                ('nama_pengguna', models.CharField(max_length=250)),
                ('email_pengguna', models.EmailField(max_length=254)),
                ('approved', models.BooleanField(default=False)),
                ('telefon_pengguna', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_ad', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
