# Generated by Django 4.0.4 on 2022-04-23 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temujanji', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TempahanSetting',
            new_name='SettingTempahan',
        ),
    ]
