# Generated by Django 4.0.4 on 2022-04-23 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temujanji', '0002_rename_tempahansetting_settingtempahan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempahan',
            name='tarikh',
            field=models.DateField(),
        ),
    ]
